### ISSUE TITLE
Entity configuration error in HA 2022.4.0

### ISSUE THREAD

**Issue by 4ib3r** [thomasgermain/vaillant-component#126]
```
Logger: homeassistant.config_entries
Source: helpers/entity_component.py:172
First occurred: 19:41:49 (1 occurrences)
Last logged: 19:41:49

Error unloading entry Multimatic for fan
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 474, in async_unload
    result = await component.async_unload_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 159, in async_unload_entry
    return await component.async_unload_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 172, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
```

```
Logger: homeassistant.components.sensor
Source: helpers/entity_registry.py:529
Integration: Sensor (documentation, issues)
First occurred: 19:48:25 (2 occurrences)
Last logged: 19:48:25

Error adding entities for domain sensor with platform multimatic
Error while setting up multimatic platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in _async_add_entity
    entry = entity_registry.async_get_or_create(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 345, in async_get_or_create
    return self.async_update_entity(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 529, in async_update_entity
    raise ValueError("entity_category must be a valid EntityCategory instance")
ValueError: entity_category must be a valid EntityCategory instance
```

**Comment by thomasgermain** [comment]
Thanks for spotting it. I'll have a look

**Comment by johanvh83** [comment]
Can confirm, I have the same exactly the same error in the log.

**Comment by eded333** [comment]
Can confirm the error log.


Logger: homeassistant.components.sensor
Source: helpers/entity_registry.py:529
Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 21:40:40 (2 occurrences)
Last logged: 21:40:40

Error adding entities for domain sensor with platform multimatic
Error while setting up multimatic platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in _async_add_entity
    entry = entity_registry.async_get_or_create(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 345, in async_get_or_create
    return self.async_update_entity(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 529, in async_update_entity
    raise ValueError("entity_category must be a valid EntityCategory instance")
ValueError: entity_category must be a valid EntityCategory instance


Logger: homeassistant.components.binary_sensor
Source: helpers/entity_registry.py:529
Integration: Binary Sensor ([documentation](https://www.home-assistant.io/integrations/binary_sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+binary_sensor%22))
First occurred: 21:40:40 (2 occurrences)
Last logged: 21:40:40

Error adding entities for domain binary_sensor with platform multimatic
Error while setting up multimatic platform for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in _async_add_entity
    entry = entity_registry.async_get_or_create(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 345, in async_get_or_create
    return self.async_update_entity(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 529, in async_update_entity
    raise ValueError("entity_category must be a valid EntityCategory instance")
ValueError: entity_category must be a valid EntityCategory instance`


Logger: homeassistant.setup
Source: setup.py:298
First occurred: 21:40:40 (1 occurrences)
Last logged: 21:40:40

Unable to prepare setup for platform multimatic.fan: Platform not found (cannot import name 'ATTR_SPEED' from 'homeassistant.components.fan' (/usr/src/homeassistant/homeassistant/components/fan/__init__.py)).

**Comment by MisfitPunisher** [comment]
Same thing Here!

2022-04-06 22:32:12 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry Multimatic for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 474, in async_unload
    result = await component.async_unload_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py", line 173, in async_unload_entry
    return await component.async_unload_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 172, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
2022-04-06 22:32:12 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry Multimatic for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 474, in async_unload
    result = await component.async_unload_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 243, in async_unload_entry
    return await component.async_unload_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 172, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
2022-04-06 22:32:12 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry Multimatic for water_heater
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 474, in async_unload
    result = await component.async_unload_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/water_heater/__init__.py", line 137, in async_unload_entry
    return await component.async_unload_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 172, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
2022-04-06 22:32:12 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry Multimatic for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 474, in async_unload
    result = await component.async_unload_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 170, in async_unload_entry
    return await component.async_unload_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 172, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
2022-04-06 22:32:12 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry Multimatic for fan
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 474, in async_unload
    result = await component.async_unload_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 159, in async_unload_entry
    return await component.async_unload_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 172, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!

**Comment by xrado** [comment]
same here

**Comment by Krzysztonek** [comment]
**... and same here:**

Logger: homeassistant.components.sensor
Source: helpers/entity_registry.py:529
Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 14:01:31 (2 occurrences)
Last logged: 14:01:31
    Error adding entities for domain sensor with platform multimatic
    Error while setting up multimatic platform for sensor
Traceback (most recent call last):
`  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in _async_add_entity
    entry = entity_registry.async_get_or_create(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 345, in async_get_or_create
    return self.async_update_entity(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 529, in async_update_entity
    raise ValueError("entity_category must be a valid EntityCategory instance")
ValueError: entity_category must be a valid EntityCategory instance`

Logger: homeassistant.components.binary_sensor
Source: helpers/entity_registry.py:529
Integration: Sensor binarny (documentation, issues)
First occurred: 14:01:31 (2 occurrences)
Last logged: 14:01:31
Error adding entities for domain binary_sensor with platform multimatic
Error while setting up multimatic platform for binary_sensor
Traceback (most recent call last):
`  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in _async_add_entity
    entry = entity_registry.async_get_or_create(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 345, in async_get_or_create
    return self.async_update_entity(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 529, in async_update_entity
    raise ValueError("entity_category must be a valid EntityCategory instance")
ValueError: entity_category must be a valid EntityCategory instance`

Logger: homeassistant.setup
Source: setup.py:298
First occurred: 14:01:30 (7 occurrences)
Last logged: 14:01:31
`Unable to prepare setup for platform multimatic.fan: Platform not found (cannot import name 'ATTR_SPEED' from 'homeassistant.components.fan' (/usr/src/homeassistant/homeassistant/components/fan/__init__.py)).`

**Comment by thomasgermain** [comment]
Version 1.12.4 fix the issue !

**Comment by 4ib3r** [comment]
Actual version is 2022.4.0, not 2022.04.0 ;-)

**Comment by thomasgermain** [comment]
> Actual version is 2022.4.0, not 2022.04.0 ;-)
> 
> Hacs don't allow install it.

Strange, it was working correctly with 2022.02.0(and not 2022.2.0) do you have any error ?

**Comment by johanvh83** [comment]
I installed your integration by HACS. So far HACS does not come up with a message to upgrade your integration...

**Comment by eded333** [comment]
The update to homeassistant 2022.4.1 has fixed the minimun version problem of 1.12.4.

**Comment by thomasgermain** [comment]
I released 1.12.5 with the correct version of  HA, so hacs can do its magic ;)
Please open a new ticket if you have an issue
